---
title: "R Notebook"
output: html_notebook
---

## Digits data set example 
```{r}


x1 <- c(2.5, 1.5, 3.5)
x2 <- c(0.75, 2.3, 3.3)
order(c(x1, x2))

```



## Shapes data set example
```{r}
load_shape <- function(i){
  base_path <- file.path("~", "mapper", "ignore", ifelse(0L == 0L, "poses", "shapes"))
  shapes <- readRDS(file = file.path(base_path, "all_shapes.rds"))
  shape_lm <- readRDS(file = file.path(base_path, "shape_lm.rds"))
  shape_mesh <- readRDS(file = file.path(base_path, "shape_mesh.rds"))
  shape_ecc <- readRDS(file = file.path(base_path, "shape_ecc.rds"))
  res <- list(xyz=shapes[[i]][shape_lm[[i]],], lm=shape_lm[[i]], mesh=shape_mesh[[i]], ecc=shape_ecc[[i]])
  return(res)
}

multiscale_shapes <- lapply(1:73, function(i){
  c_shape <- load_shape(i) # 22 == elephant, out of 73 
  m <- Mapper::MapperRef$new(X = c_shape$xyz)$
    use_cover(filter_values = matrix(c_shape$ecc), number_intervals=15L, percent_overlap=0)
  mm <- multiscale(m, max_dim = 1L, max_overlap = 65, time = "overlap")
  mm_bar <- Simpers::simpers(mm$initial_mapper, sm = mm$simplicial_maps)
  list(mm, mm_bar)
})

# ms_saved <- lapply(multiscale_shapes, function(ms){
#   ms[[1]]$initial_mapper_ser <- ms[[1]]$initial_mapper$serialize()
# })
# saveRDS(ms_saved, "ms_saved.rds")

dgms <- lapply(multiscale_shapes, function(ms){
  do.call(cbind, ms[[2]][c("dim", "birth", "death")])
})

idx <- seq(length(dgms))
dgm_dist <- apply(expand.grid(idx, idx), 1, function(ij){
  TDA::bottleneck(dgms[[ij[1]]], dgms[[ij[2]]], dimension = 0)
})
dgm_mat <- matrix(dgm_dist, nrow = 73, ncol = 73)
dgm_mat[dgm_mat == Inf] <- max(dgm_mat[dgm_mat != Inf])*2
image(dgm_mat, col = rev(heat.colors(100)))

```

```{r}

```

