# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test_merge <- function(data) {
    .Call(`_Mapper_test_merge`, data)
}

test_merge2 <- function(data) {
    .Call(`_Mapper_test_merge2`, data)
}

valid_pairs <- function(level_set_pairs) {
    .Call(`_Mapper_valid_pairs`, level_set_pairs)
}

constructLevelSetIndex <- function(x, bnds) {
    .Call(`_Mapper_constructLevelSetIndex`, x, bnds)
}

constructIsoAlignedLevelSets <- function(x, bnds, save_bounds = TRUE) {
    .Call(`_Mapper_constructIsoAlignedLevelSets`, x, bnds, save_bounds)
}

constructFixedLevelSets <- function(filter_values, index_set, overlap, number_intervals, filter_range, filter_len) {
    .Call(`_Mapper_constructFixedLevelSets`, filter_values, index_set, overlap, number_intervals, filter_range, filter_len)
}

constructRestrainedLevelSets <- function(filter_values, index_set, interval_length, step_size, filter_min) {
    .Call(`_Mapper_constructRestrainedLevelSets`, filter_values, index_set, interval_length, step_size, filter_min)
}

createCoverMap <- function(ls1, ls2, d) {
    .Call(`_Mapper_createCoverMap`, ls1, ls2, d)
}

edgelist_to_adjacencylist <- function(el) {
    .Call(`_Mapper_edgelist_to_adjacencylist`, el)
}

findFirstEqual <- function(x, value) {
    .Call(`_Mapper_findFirstEqual`, x, value)
}

dist_to_boxes <- function(positions, interval_length, num_intervals, dist_to_lower, dist_to_upper) {
    .Call(`_Mapper_dist_to_boxes`, positions, interval_length, num_intervals, dist_to_lower, dist_to_upper)
}

dist_subset <- function(dist, idx) {
    .Call(`_Mapper_dist_subset`, dist, idx)
}

concatDist <- function(dist, n_new, new_dists) {
    .Call(`_Mapper_concatDist`, dist, n_new, new_dists)
}

dist_from_to <- function(X_query, X_ref) {
    .Call(`_Mapper_dist_from_to`, X_query, X_ref)
}

gh_make_A <- function(idx) {
    .Call(`_Mapper_gh_make_A`, idx)
}

gh_make_Q <- function(x_dist, y_dist) {
    .Call(`_Mapper_gh_make_Q`, x_dist, y_dist)
}

all_correspondences <- function(X, Y) {
    .Call(`_Mapper_all_correspondences`, X, Y)
}

landmark_maxmin <- function(x, n, seed = 0L) {
    .Call(`_Mapper_landmark_maxmin`, x, n, seed)
}

nondecreasing_seq <- function(lst) {
    .Call(`_Mapper_nondecreasing_seq`, lst)
}

connected_pullbacks <- function(pullback_ids, pullback, stree) {
    .Call(`_Mapper_connected_pullbacks`, pullback_ids, pullback, stree)
}

build_0_skeleton <- function(pullback_ids, cluster_f, level_set_f, vertices, pullback, stree) {
    .Call(`_Mapper_build_0_skeleton`, pullback_ids, cluster_f, level_set_f, vertices, pullback, stree)
}

build_1_skeleton <- function(pullback_ids, min_sz, vertices, pullback, stree, modify) {
    .Call(`_Mapper_build_1_skeleton`, pullback_ids, min_sz, vertices, pullback, stree, modify)
}

build_k_skeleton <- function(pullback_ids, pullback, vertices, k, stree, modify) {
    .Call(`_Mapper_build_k_skeleton`, pullback_ids, pullback, vertices, k, stree, modify)
}

build_flag_complex <- function(k, stree) {
    invisible(.Call(`_Mapper_build_flag_complex`, k, stree))
}

intersectNodes <- function(nodes1, nodes2, node_ids1, node_ids2) {
    .Call(`_Mapper_intersectNodes`, nodes1, nodes2, node_ids1, node_ids2)
}

