# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

make_cartesian_product <- function(vecs) {
    .Call('_Mapper_make_cartesian_product', PACKAGE = 'Mapper', vecs)
}

valid_pairs <- function(level_set_pairs) {
    .Call('_Mapper_valid_pairs', PACKAGE = 'Mapper', level_set_pairs)
}

constructLevelSetIndex <- function(x, bnds) {
    .Call('_Mapper_constructLevelSetIndex', PACKAGE = 'Mapper', x, bnds)
}

constructIsoAlignedLevelSets <- function(x, bnds, save_bounds = TRUE) {
    .Call('_Mapper_constructIsoAlignedLevelSets', PACKAGE = 'Mapper', x, bnds, save_bounds)
}

constructFixedLevelSets <- function(filter_values, index_set, overlap, number_intervals, filter_range, filter_len) {
    .Call('_Mapper_constructFixedLevelSets', PACKAGE = 'Mapper', filter_values, index_set, overlap, number_intervals, filter_range, filter_len)
}

constructRestrainedLevelSets <- function(filter_values, index_set, interval_length, step_size, filter_min) {
    .Call('_Mapper_constructRestrainedLevelSets', PACKAGE = 'Mapper', filter_values, index_set, interval_length, step_size, filter_min)
}

createCoverMap <- function(ls1, ls2, d) {
    .Call('_Mapper_createCoverMap', PACKAGE = 'Mapper', ls1, ls2, d)
}

edgelist_to_adjacencylist <- function(el) {
    .Call('_Mapper_edgelist_to_adjacencylist', PACKAGE = 'Mapper', el)
}

findFirstEqual <- function(x, value) {
    .Call('_Mapper_findFirstEqual', PACKAGE = 'Mapper', x, value)
}

nodeMap <- function(node_lsfi1, node_lsfi2, cover_map) {
    .Call('_Mapper_nodeMap', PACKAGE = 'Mapper', node_lsfi1, node_lsfi2, cover_map)
}

dist_to_boxes <- function(positions, interval_length, num_intervals, dist_to_lower, dist_to_upper) {
    .Call('_Mapper_dist_to_boxes', PACKAGE = 'Mapper', positions, interval_length, num_intervals, dist_to_lower, dist_to_upper)
}

dist_subset <- function(dist, idx) {
    .Call('_Mapper_dist_subset', PACKAGE = 'Mapper', dist, idx)
}

concatDist <- function(dist, n_new, new_dists) {
    .Call('_Mapper_concatDist', PACKAGE = 'Mapper', dist, n_new, new_dists)
}

dist_from_to <- function(X_query, X_ref) {
    .Call('_Mapper_dist_from_to', PACKAGE = 'Mapper', X_query, X_ref)
}

index_test <- function(sizes) {
    .Call('_Mapper_index_test', PACKAGE = 'Mapper', sizes)
}

createUpdateBlocks <- function(G, overlap_blocks, n_lvl_sets, n_blocks, n) {
    .Call('_Mapper_createUpdateBlocks', PACKAGE = 'Mapper', G, overlap_blocks, n_lvl_sets, n_blocks, n)
}

test_merge <- function(data) {
    .Call('_Mapper_test_merge', PACKAGE = 'Mapper', data)
}

test_merge2 <- function(data) {
    .Call('_Mapper_test_merge2', PACKAGE = 'Mapper', data)
}

check_connected <- function(ls_to_check, ls_vertex_map, vertices, stree) {
    .Call('_Mapper_check_connected', PACKAGE = 'Mapper', ls_to_check, ls_vertex_map, vertices, stree)
}

build_0_skeleton <- function(which_levels, X, f, level_sets, vertices, ls_vertex_map, stree) {
    .Call('_Mapper_build_0_skeleton', PACKAGE = 'Mapper', which_levels, X, f, level_sets, vertices, ls_vertex_map, stree)
}

build_1_skeleton <- function(ls_pairs, vertices, ls_vertex_map, stree) {
    invisible(.Call('_Mapper_build_1_skeleton', PACKAGE = 'Mapper', ls_pairs, vertices, ls_vertex_map, stree))
}

intersectNodes <- function(nodes1, nodes2, node_ids1, node_ids2) {
    .Call('_Mapper_intersectNodes', PACKAGE = 'Mapper', nodes1, nodes2, node_ids1, node_ids2)
}

update_level_sets <- function(which_levels, ms, X, f, vertices, ls_vertex_map, stree) {
    .Call('_Mapper_update_level_sets', PACKAGE = 'Mapper', which_levels, ms, X, f, vertices, ls_vertex_map, stree)
}

test_it <- function(x) {
    .Call('_Mapper_test_it', PACKAGE = 'Mapper', x)
}

test_map <- function(index_set) {
    invisible(.Call('_Mapper_test_map', PACKAGE = 'Mapper', index_set))
}

